fix: Update babel core based on error message
Full error message: 🚨 Build failed. @parcel/transformer-babel: babelCore(...).loadPartialConfigAsync is not a function TypeError: babelCore(...).loadPartialConfigAsync is not a function     at load (/workspaces/algorithms-exercises/node_modules/@parcel/transformer-babel/lib/config.js:115:41)     at loadConfig (/workspaces/algorithms-exercises/node_modules/@parcel/transformer-babel/lib/BabelTransformer.js:66:30)     at Transformation.loadTransformerConfig (/workspaces/algorithms-exercises/node_modules/@parcel/core/lib/Transformation.js:741:13)     at Transformation.loadPipeline (/workspaces/algorithms-exercises/node_modules/@parcel/core/lib/Transformation.js:679:31)     at async Transformation.loadNextPipeline (/workspaces/algorithms-exercises/node_modules/@parcel/core/lib/Transformation.js:717:24)     at async Transformation.runPipelines (/workspaces/algorithms-exercises/node_modules/@parcel/core/lib/Transformation.js:434:24)     at async Transformation.run (/workspaces/algorithms-exercises/node_modules/@parcel/core/lib/Transformation.js:316:19)     at async Child.handleRequest (/workspaces/algorithms-exercises/node_modules/@parcel/workers/lib/child.js:255:9) @JackHowa ➜ /workspaces/algorithms-exercises (main ✗) $ npm i npm WARN @babel/helper-define-polyfill-provider@0.2.3 requires a peer of @babel/core@^7.4.0-0 but none is installed. You must install peer dependencies yourself. npm WARN @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.13.12 requires a peer of @babel/core@^7.13.0 but none is installed. You must install peer dependencies yourself. npm WARN @babel/plugin-proposal-class-static-block@7.14.3 requires a peer of @babel/core@^7.12.0 but none is installed. You must install peer dependencies yourself. npm WARN @parcel/babel-preset-env@2.0.0-beta.2 requires a peer of @babel/core@^7.12.0 but none is installed. You must install peer dependencies yourself. npm WARN @parcel/transformer-babel@2.0.0-beta.2 requires a peer of @babel/core@^7.12.0 but none is installed. You must install peer dependencies yourself. npm WARN algorithms-exercises@1.0.0 No repository field. npm WARN algorithms-exercises@1.0.0 No license field. npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})  audited 1455 packages in 6.245s  142 packages are looking for funding   run `npm fund` for details